// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/da5d70b6cbae24ee6f53a51f34b32f6d81b31deb/df-visible/df-visible.d.ts
interface JQuery {
   /**
    * Gets the value of a setting.
    * @param details Which setting to consider.
    * @param callback The callback parameter should be a function that looks like this:
    * function(object details) {...};
    */
	visible(partial?: boolean, hidden?: boolean, direction?: string): boolean;
}